#eureka注册中心
eureka:
  instance:
    # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-renewal-interval-in-seconds: 10
    # Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 30
    hostname: 127.0.0.1
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000/ms-eureka/eureka/
  server:
    #自我保护模式关闭
    enable-self-preservation: false
    # 每隔 4 秒清理服务列表 （默认值 60*1000 是1分钟）
    eviction-interval-timer-in-ms: 3000
logging:
  level:
    com.netflix: warn
