spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: WUAJhprEIT6dGqQceIvRDnZq23pBoe20f+AUWjV10TmrZ1xXQt+lxWouSXhElwoahBdeiPt0XnQY57TEEPu6mQ==
    key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJQcNhpntbPAYYV0HWjsTdTKzTzLvytSKcZR5V6MsnSE2KHcDfT69cLm5qVSSgePD3olKuK98nyN5J7wIux0VMCAwEAAQ==
  redis:
    host: localhost
    password: admin
    #port: 6379
    port: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/ms-eureka/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:9001

swagger:
  enabled: true

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/**/*.xml
  #注意：对应实体类的路径
  type-aliases-package: com.microservice.member.bean
